import Head from 'next/head'
import { Fragment } from 'react'

function form() {
    return (
        <Fragment>
            <Head>
            <title>Payment form</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            

        </Fragment>
    )
}
export default form